name: Build & Deploy Spring App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot Pos API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Print Test Results
        if: failure()
        run: cat target/surefire-reports/*.txt

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Build The Application
        run: |
          mvn clean
          mvn -B package --file pom.xml
