name: Build & Deploy Spring App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot Pos API
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Unit Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/pos_api_system_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Agtsj123##
        run: mvn -B test --file pom.xml

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Build The Application
        run: |
          mvn clean
          mvn -B package --file pom.xml
